obj-m := KRdmaKitSyscall.o
KRdmaKitSyscall-objs := KRdmaKitSyscall.rust.o

CARGO ?= cargo
TARGET ?= x86_64-unknown-none-linuxkernel

export c_flags

$(src)/target/$(TARGET)/debug/libKRdmaKitSyscall.a: cargo_will_determine_dependencies
	cd $(src); $(CARGO) build -Z build-std=core,alloc --target=$(TARGET)

.PHONY: cargo_will_determine_dependencies

%.rust.o: target/$(TARGET)/debug/lib%.a
	$(LD) -r -o $@ --whole-archive $<
