#ifndef COMPAT_BIT_H
#define COMPAT_BIT_H

#include_next <linux/bit.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"

#ifndef GENMASK 
#define GENMASK(h, l) \
	(((~0UL) - (1UL << (l)) + 1) & (~0UL >> (BITS_PER_LONG - 1 - (h))))
#endif

#endif /* COMPAT_BIT_OPS_H */
