#ifndef COMPAT_FILE_H
#define COMPAT_FILE_H

#include_next <linux/file.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"

#ifndef HAVE_GET_UNUSED_FD_FLAGS
/* some RH kernels have backported get_unused_fd_flags that uses
 * an unexported funciton, so we cannot use it, undef it
 * */
#ifdef get_unused_fd_flags
#undef get_unused_fd_flags
#endif

#define get_unused_fd_flags(a) get_unused_fd()
#endif

#endif /* COMPAT_FILE_H */
