#ifndef _COMPAT_LINUX_FIRMWARE_H
#define _COMPAT_LINUX_FIRMWARE_H

#include_next <linux/firmware.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"

#ifndef HAVE_REQUEST_FIRMWARE_DIRECT
#define request_firmware_direct        request_firmware
#endif

#endif /* _COMPAT_LINUX_FIRMWARE_H */
