#ifndef COMPAT_FS_H
#define COMPAT_FS_H

#include_next <linux/fs.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"

#ifndef get_file_rcu
#define get_file_rcu_many(x, cnt)       \
        atomic_long_add_unless(&(x)->f_count, (cnt), 0)
#define get_file_rcu(x) get_file_rcu_many((x), 1)
#endif

#endif /* COMPAT_FS_H */
