obj-m := testmodule.o
testmodule-objs := $(TEST_NAME).rust.o

CARGO ?= cargo

export c_flags
export UTEST

$(src)/target/x86_64-unknown-none-linuxkernel/debug/lib%.a: cargo_will_determine_dependencies
	cd $(src)/$(TEST_PATH); CARGO_TARGET_DIR=../target $(CARGO) build -Z build-std=core,alloc --target=x86_64-unknown-none-linuxkernel

.PHONY: cargo_will_determine_dependencies

%.rust.o: target/x86_64-unknown-none-linuxkernel/debug/lib%.a
	$(LD) -r -o $@ --whole-archive $<
